apiVersion: apps/v1
kind: Deployment
metadata:
  name: krystal-ns-deployment
  labels:
    app: krystal-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krystal-ns
  template:
    metadata:
      labels:
        app: krystal-ns
    spec:
      containers:
        - name: krystal-ns
          image: krystal-ns:latest
          ports:
          - containerPort: 8080
          imagePullPolicy: Never
